#!/usr/bin/env bash
# shellcheck disable=SC2086
# Information about server domains

# Function to check domain information
check_domain() {
    local domain="$1"
    local subdomain="$2"
    local full_domain="$subdomain.$domain"

    local record_type=$(dig +short "$full_domain" | grep -Eo '^[0-9.]+$' && echo "A" || echo "CNAME")
    local destination=$(dig +short "$full_domain")

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main function
main() {
    local domain="$1"
    local subdomain="$2"

    # Default subdomains
    local subdomains=("www" "lb-01" "web-01" "web-02")

    if [ -z "$subdomain" ]; then
        for sub in "${subdomains[@]}"; do
            check_domain "$domain" "$sub"
        done
    else
        check_domain "$domain" "$subdomain"
    fi
}

# Check for correct number of arguments
if [ "$#" -eq 1 ] || [ "$#" -eq 2 ]; then
    main "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
