#!/usr/bin/env bash
# print domains and subdomains

print_domain_subdomain() {
    local subdomain="$1"
    local domain="$2"
    local full_domain="$subdomain.$domain"
    
    local record_type=$(dig +short "$full_domain" | grep -Eo '^[0-9.]+$' && echo "A" || echo "CNAME")
    local destination=$(dig +short "$full_domain")

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$2" "$1"
else
    default_subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${default_subdomains[@]}"; do
        print_domain_subdomain "$subdomain" "$1"
    done
fi
