#!/usr/bin/env bash

# Update package repository and install Nginx
apt-get update
apt-get -y install nginx

# Configure Nginx redirection
SERVER_CONFIG=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}"

# Create a temporary configuration file
echo -e "$SERVER_CONFIG" > /etc/nginx/sites-available/redirect

# Create a symbolic link to enable the site configuration
ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Test Nginx configuration and restart the service
nginx -t && service nginx restart
