#!/usr/bin/env bash
# Script to install and configure HAProxy as a load balancer

# Update package list and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
CONFIG_FILE="/etc/haproxy/haproxy.cfg"
sudo cp "$CONFIG_FILE" "${CONFIG_FILE}.backup" # Backup the original configuration file

# Replace [STUDENT_ID] with actual IP addresses
echo "
frontend web_front
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server web-01 100.25.220.119:80 check
    server web-02 100.25.147.34:80 check" | sudo tee "$CONFIG_FILE"

# Restart HAProxy
sudo service haproxy restart

# Enable HAProxy to be managed via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy again to apply changes
sudo service haproxy restart
